"""Mock OPC UA server used by tests/test_opcua_client.cpp.

Stands in for a real FESA-side OPC UA server so the OpcUa::OpcUaClient /
OpcUa::OpcUaClientRegistry test suite (include/OpcUa/OpcUaClient.hpp) can run
against a live server without any real hardware.

Runs *two* independent asyncua Server instances, on two different ports:

  - PLAIN_ENDPOINT (opc.tcp://127.0.0.1:4840): SecurityPolicy#None only, no
    certificate loaded. Matches OpcUaClient's default config and the
    allowNonePolicyPassword override it sets for username/password auth over
    None (see OpcUaClient::applyUsernameIdentityToken()).
  - SECURE_ENDPOINT (opc.tcp://127.0.0.1:4843): SecurityPolicy#Basic256Sha256
    only, in both Sign and SignAndEncrypt modes, using
    scripts/certs/server_cert.der/server_key.pem (generated by
    sslcert-create.sh). Matches OpcUa::SecurityCredentials /
    OpcUaClient's encryption-enabled constructors.

These are deliberately two separate servers/ports rather than one server
offering both None and Basic256Sha256 side by side: asyncua, once a
certificate is loaded, automatically upgrades the *None*-mode endpoint's
UserNameIdentityToken to require an encrypting SecurityPolicy too (to avoid
ever sending a password in plaintext - see server.py's `_set_endpoints()`),
which would silently break the plain SecurityPolicy#None username/password
tests that intentionally rely on OpcUaClient's allowNonePolicyPassword
override. Splitting the two concerns onto separate servers avoids that
interaction entirely and keeps each endpoint's behaviour simple to reason
about. This server does not validate the client's certificate (asyncua's
certificate_validator hook is simply left unset) - fine for exercising the
*client's* encryption behaviour, but not a stand-in for a production
server's own trust policy.

Usage:
    python3 scripts/mock_server.py

Then, from the build directory, run the test suite:
    ctest --output-on-failure
    # or: ./opcua_client_tests

Namespace: index 3 on both servers (see the "dummy namespace" comment in
register_variables() for why) - so OpcUaClient's default nodeIdNamespace
works against either endpoint without change.

Variable nodes exposed on *both* servers (NodeId is the quoted tag name,
matching what OpcUaClient::quote() produces for a plain, dot-free tag):

    NodeId                                              UA type  Initial   Exercised via tag
    "TestBool"                                          Boolean  True      "TestBool"
    "TestByte"                                          Byte     255       "TestByte"
    "A_OUT_0"                                            Int16    -15000    "A_OUT_0"
    "A_OUT_1"                                            Int16    -15001    "A_OUT_1"
    "A_OUT_2"                                            Int16    -15002    "A_OUT_2"
    "TestInt32"                                         Int32    123456789 "TestInt32"
    "PID_Setpoint"                                       Float    45.5      "PID_Setpoint"
    "HMIinterface"."02-NG02"."TFT_Anzeige_NG2Ist1U"     Int32    777       "HMIinterface.02-NG02.TFT_Anzeige_NG2Ist1U"

A_OUT_1/A_OUT_2 exist alongside A_OUT_0 solely so the batch-read/write tests
(OpcUaClientBatchTest in test_opcua_client.cpp) have more than one node of
the same type to actually batch together.

The last node's NodeId is exactly what OpcUaClient::quote() produces for the
dot-separated tag "HMIinterface.02-NG02.TFT_Anzeige_NG2Ist1U" (see the
worked example in OpcUaClient::quote()'s doc comment) - each dot-delimited
segment quoted independently and joined back with dots, e.g.
'"HMIinterface"."02-NG02"."TFT_Anzeige_NG2Ist1U"'. It exists specifically so
that read<T>()/write<T>() calls using the unquoted, dotted tag name are
verified end-to-end against a real server, not just at the quote() unit-test
level. The two servers have independent address spaces (they are separate
InternalServer instances), so the node is registered on each separately by
the shared register_variables() helper - they do not share state.
"""

import asyncio
import logging
from pathlib import Path

from asyncua import Server, ua
from asyncua.server.user_managers import User, UserRole

# Configure main logger
logging.basicConfig(level=logging.INFO)

# Suppress noisy internal address space warnings from asyncua
logging.getLogger("asyncua.server.address_space").setLevel(logging.WARNING)
logging.getLogger("asyncua.server.internal_server").setLevel(logging.WARNING)

_logger = logging.getLogger("mock_server")

PLAIN_ENDPOINT = "opc.tcp://127.0.0.1:4840"
SECURE_ENDPOINT = "opc.tcp://127.0.0.1:4843"

# Credentials accepted for username/password authentication.
# Kept in sync with the values used in test_opcua_client.cpp.
VALID_USERS = {
    "testuser": "testpass",
}

# Server identity for SECURE_ENDPOINT, generated by scripts/sslcert-create.sh.
# SERVER_APPLICATION_URI must match the "URI:urn:fesa:mockserver"
# SubjectAlternativeName entry sslcert-create.sh bakes into
# SERVER_CERTIFICATE - asyncua only warns on a mismatch, but a real client's
# certificate validation may reject it outright.
CERTS_DIR = Path(__file__).resolve().parent / "certs"
SERVER_CERTIFICATE = CERTS_DIR / "server_cert.der"
SERVER_PRIVATE_KEY = CERTS_DIR / "server_key.pem"
SERVER_APPLICATION_URI = "urn:fesa:mockserver"


class MockUserManager:
    """Validates incoming client authentication credentials.

    asyncua calls get_user() for every session, including anonymous ones
    (username/password are None in that case), so anonymous access must be
    granted explicitly here for the existing, non-auth tests to keep
    working against this same server instance.

    Both anonymous and authenticated sessions are granted the Admin role.
    asyncua's default permission ruleset only allows Admin-role users to
    write (and User/Admin to read) - plain Anonymous has no read/write
    rights at all, which would break every read/write test. This server is
    only meant to test *authentication* (who can open a session), not
    fine-grained authorization, so both paths get full access once a
    session is established.
    """

    def get_user(self, iserver, username=None, password=None, certificate=None):
        """Called by asyncua for every session; return a User to admit it, None to reject."""
        if username is None and password is None:
            return User(role=UserRole.Admin)

        if VALID_USERS.get(username) == password:
            _logger.info(f"Authenticated user '{username}'")
            return User(role=UserRole.Admin)

        _logger.warning(f"Rejected authentication for user '{username}'")
        return None


async def register_variables(server: Server) -> None:
    """Register the shared set of test variable nodes on `server`.

    Used by both the plain and secure servers so either endpoint exposes the
    same tags at the same (quoted) NodeIds - see the module docstring's node
    table.
    """
    # register_namespace() assigns indices sequentially starting at 2 (ns0 is
    # the OPC UA standard namespace, ns1 the server's own default namespace).
    # This throwaway registration exists solely to push our real namespace to
    # index 3, matching OpcUaClient's default nodeIdNamespace constructor
    # argument - so tests can rely on that default instead of having to pass
    # an explicit namespace index everywhere.
    await server.register_namespace("http://dummy.namespace.2")
    idx = await server.register_namespace("http://fesa.mock.server/opcua")

    _logger.info(f"[{server.endpoint.geturl()}] Target Namespace Index: {idx}")

    objects = server.nodes.objects

    # Each node's NodeId is a quoted string, e.g. '"TestBool"' - this is what
    # OpcUaClient::quote() produces for a plain (dot-free) tag name, so a
    # client calling read<T>("TestBool") / write<T>("TestBool", ...) resolves
    # straight to the node below with no further translation needed.
    node_bool = await objects.add_variable(ua.NodeId('"TestBool"', idx), "TestBool", True, varianttype=ua.VariantType.Boolean)
    await node_bool.set_writable()

    node_byte = await objects.add_variable(ua.NodeId('"TestByte"', idx), "TestByte", 255, varianttype=ua.VariantType.Byte)
    await node_byte.set_writable()

    node_int16 = await objects.add_variable(ua.NodeId('"A_OUT_0"', idx), "A_OUT_0", -15000, varianttype=ua.VariantType.Int16)
    await node_int16.set_writable()

    # A_OUT_1/A_OUT_2: same type as A_OUT_0, purely so the batch-read/write
    # tests have several same-typed nodes to actually batch together.
    node_int16_1 = await objects.add_variable(ua.NodeId('"A_OUT_1"', idx), "A_OUT_1", -15001, varianttype=ua.VariantType.Int16)
    await node_int16_1.set_writable()

    node_int16_2 = await objects.add_variable(ua.NodeId('"A_OUT_2"', idx), "A_OUT_2", -15002, varianttype=ua.VariantType.Int16)
    await node_int16_2.set_writable()

    node_int32 = await objects.add_variable(ua.NodeId('"TestInt32"', idx), "TestInt32", 123456789, varianttype=ua.VariantType.Int32)
    await node_int32.set_writable()

    node_float = await objects.add_variable(ua.NodeId('"PID_Setpoint"', idx), "PID_Setpoint", 45.5, varianttype=ua.VariantType.Float)
    await node_float.set_writable()

    # Multi-segment NodeId covering OpcUaClient::quote()'s dot-separated tag
    # path support: the identifier string below is the literal output of
    # quote("HMIinterface.02-NG02.TFT_Anzeige_NG2Ist1U"), i.e. each
    # dot-delimited segment quoted independently and rejoined with dots.
    node_dotted = await objects.add_variable(
        ua.NodeId('"HMIinterface"."02-NG02"."TFT_Anzeige_NG2Ist1U"', idx),
        "HMIinterface.02-NG02.TFT_Anzeige_NG2Ist1U",
        777,
        varianttype=ua.VariantType.Int32,
    )
    await node_dotted.set_writable()


async def make_plain_server() -> Server:
    """Build the SecurityPolicy#None-only server (unchanged from before security support was added)."""
    server = Server(user_manager=MockUserManager())
    await server.init()

    server.set_endpoint(PLAIN_ENDPOINT)

    # Accept both Anonymous and UserName identity tokens on the same
    # endpoint, so existing anonymous tests and username/password auth tests
    # can run against the same server instance.
    server.set_identity_tokens([ua.AnonymousIdentityToken, ua.UserNameIdentityToken])

    await register_variables(server)
    return server


async def make_secure_server() -> Server:
    """Build the SecurityPolicy#Basic256Sha256-only (Sign + SignAndEncrypt) server."""
    if not SERVER_CERTIFICATE.exists() or not SERVER_PRIVATE_KEY.exists():
        raise FileNotFoundError(
            f"Missing mock server certificate/key ({SERVER_CERTIFICATE}, {SERVER_PRIVATE_KEY}). "
            "Run scripts/sslcert-create.sh (from within scripts/) to generate them first."
        )

    server = Server(user_manager=MockUserManager())
    await server.init()

    server.set_endpoint(SECURE_ENDPOINT)
    server.set_identity_tokens([ua.AnonymousIdentityToken, ua.UserNameIdentityToken])

    # Must match the ApplicationUri SAN entry embedded in SERVER_CERTIFICATE -
    # see the SERVER_APPLICATION_URI comment above.
    await server.set_application_uri(SERVER_APPLICATION_URI)
    await server.load_certificate(str(SERVER_CERTIFICATE))
    await server.load_private_key(str(SERVER_PRIVATE_KEY))

    # No SecurityPolicyType.NoSecurity here on purpose - see the module
    # docstring for why the None and Basic256Sha256 endpoints are kept on
    # separate servers entirely. asyncua would otherwise also advertise
    # Aes128Sha256RsaOaep/Aes256Sha256RsaPss, which OpcUaClient never
    # requests; narrowing the list keeps the endpoint set deterministic.
    server.set_security_policy([
        ua.SecurityPolicyType.Basic256Sha256_Sign,
        ua.SecurityPolicyType.Basic256Sha256_SignAndEncrypt,
    ])

    await register_variables(server)
    return server


async def main():
    """Configure and run both mock servers until interrupted (Ctrl+C)."""
    plain_server = await make_plain_server()
    secure_server = await make_secure_server()

    _logger.info(f"Plain mock OPC UA server running on {PLAIN_ENDPOINT} ...")
    _logger.info(f"Secure mock OPC UA server running on {SECURE_ENDPOINT} ...")
    async with plain_server, secure_server:
        while True:
            await asyncio.sleep(1)

if __name__ == "__main__":
    asyncio.run(main())
